# Generated by Django 5.0.4 on 2024-04-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQI', '0003_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='co',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='no2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='o3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pm10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pm25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='so2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
